"""empty message

Revision ID: 2fcb08dfc5ff
Revises: 
Create Date: 2022-08-12 20:52:34.051277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fcb08dfc5ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adjectives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('designs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('design_names', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('adjective',
    sa.Column('design_id', sa.Integer(), nullable=True),
    sa.Column('adjective_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['adjective_id'], ['adjectives.id'], ),
    sa.ForeignKeyConstraint(['design_id'], ['designs.id'], )
    )
    op.create_table('design',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('design_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['design_id'], ['designs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('design')
    op.drop_table('adjective')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('designs')
    op.drop_table('adjectives')
    # ### end Alembic commands ###
